server:
  port: 8080
dubbo:
  protocol:
    name: dubbo
    port: -1
#  provider:
#    loadbalance: roundrobin
  registry:
    address: spring-cloud://127.0.0.1
  cloud:
    subscribed-services: dubbo-api
  consumer:
    filter: requestHandlerInterceptorConfig
spring:
  application:
    name: dubbo-demo
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true